.TH PRAM 9 "2020-04-25" "pram 9"

.SH NAME
PRam \- Tool to ease merging Pull Requests and git patches

.SH SYNOPSIS
.B pram
[\fI<options>\fP] \fI<pr-number|pr-url|patch-url>\fP...

.SH DESCRIPTION
Merge specified GitHub PR(s) into the repository in current directory.

.SH OPTIONS
.TP
\fB\-\-am\-options\fR \fIOPTIONS\fP
Pass additional options to git am
.TP
\fB\-b\fR \fIBUG\fP, \fB\-\-bug\fR \fIBUG\fP, \fB\-c\fR \fIBUG\fP, \fB\-\-closes\fR \fIBUG\fP
Reference or close the specific bug, takes either a bug number or URL, can be
specified multiple times.
.TP
\fB\-e\fR \fIEDITOR\fP, \fB\-\-editor\fP \fIEDITOR\fP
Override the editor used (default: ${EDITOR})
.TP
\fB\-\-no\-gitconfig\fR
Do not query options via git config.
.TP
\fB\-G\fR, \fB\-\-no\-gpgsign\fR
Do not automatically GPG-sign commits
.TP
\fB\-I\fR, \fB\-\-non-interactive\fR
Do not interactively ask to merge, just do it."
.TP
\fB\-r\fR \fIREPO\fR, \fB\-\-repository\fR \fIREPO\fP
GitHub repo to use (default: gentoo/gentoo)
.TP
\fB\-s\fR, \fB\-\-signoff\fR
Add Signed-off-by to commits (the default)
.TP
\fB-S\fR, \fB\-\-no\-signoff\fR
Disable adding Signed-off-by to commits

.SH PARAMETERS
.IP \fI<pr-number>\fP
GitHub PR number
.IP \fI<pr-url>\fP
Full URL to the pull request
.IP \fI<patch-url>\fP
URL to a patch file

.SH GIT CONFIG SUPPORT
PRam queries configuration via \fBgit config\fR by default.  It makes it
possible to specify additional options globally via \fB~/.gitconfig\fR
and per-repo via \fB.git/config\fR.  Command-line options override configuration
files.

The following options are currently supported:
.TP
string options:
\fIpram.editor\fR, \fIpram.repository\fR
.TP
boolean options (\fB--type bool\fR):
\fIpram.gpgsign\fR, \fIpram.interactive\fR, \fIpram.signoff\fR

.SH LICENSE
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

.SH AUTHOR
.B PRam
was written by Michał Górny <mgorny@gentoo.org>
